name: Build Protobuf Android (arm64-v8a)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout protobuf source
        uses: actions/checkout@v4
        with:
          repository: protocolbuffers/protobuf
          path: protobuf

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build unzip wget

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk
          echo "NDK=$HOME/android-ndk" >> $GITHUB_ENV

      - name: Configure CMake for arm64-v8a
        run: |
          cd protobuf
          git submodule update --init --recursive
          mkdir -p cmake_build && cd cmake_build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-21 \
            -Dprotobuf_BUILD_TESTS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -Dprotobuf_BUILD_SHARED_LIBS=ON \
            -G Ninja

      - name: Build libprotobuf.so
        run: |
          cd protobuf/cmake_build
          ninja

      - name: Upload libprotobuf.so
        uses: actions/upload-artifact@v4
        with:
          name: libprotobuf-arm64-v8a
          path: protobuf/cmake_build/*.so
