name: Build Protobuf Android (static libs)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    steps:
      - name: Checkout protobuf source
        uses: actions/checkout@v4
        with:
          repository: protocolbuffers/protobuf
          path: protobuf

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build unzip wget

      - name: Download Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q android-ndk-r26d-linux.zip
          mv android-ndk-r26d $HOME/android-ndk
          echo "NDK=$HOME/android-ndk" >> $GITHUB_ENV

      - name: Configure CMake for ${{ matrix.abi }}
        run: |
          cd protobuf
          git submodule update --init --recursive
          mkdir -p build-${{ matrix.abi }}
          cd build-${{ matrix.abi }}
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ matrix.abi }} \
            -DANDROID_PLATFORM=android-21 \
            -Dprotobuf_BUILD_TESTS=OFF \
            -DCMAKE_BUILD_TYPE=Release \
            -Dprotobuf_BUILD_SHARED_LIBS=OFF \
            -G Ninja

      - name: Build libprotobuf.a (${{ matrix.abi }})
        run: |
          cd protobuf/build-${{ matrix.abi }}
          ninja

      - name: Prepare artifact folder
        run: |
          mkdir -p out/lib
          mkdir -p out/include
          # находим libprotobuf.a
          LIB=$(find protobuf/build-${{ matrix.abi }} -name "libprotobuf.a" | head -n 1)
          cp "$LIB" out/lib/
          cp -r protobuf/src/* out/include/

      - name: Upload per-ABI artifact
        uses: actions/upload-artifact@v4
        with:
          name: libprotobuf-${{ matrix.abi }}
          path: out

  package:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Download all ABI artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Organize files
        run: |
          mkdir -p protobuf-android-libs/include
          mkdir -p protobuf-android-libs/libs

          # копируем include (берём из arm64-v8a, он одинаковый для всех)
          cp -r artifacts/libprotobuf-arm64-v8a/include/* protobuf-android-libs/include/

          # копируем либы по ABI
          mkdir -p protobuf-android-libs/libs/armeabi-v7a
          mkdir -p protobuf-android-libs/libs/arm64-v8a
          mkdir -p protobuf-android-libs/libs/x86
          mkdir -p protobuf-android-libs/libs/x86_64

          cp artifacts/libprotobuf-armeabi-v7a/lib/libprotobuf.a protobuf-android-libs/libs/armeabi-v7a/
          cp artifacts/libprotobuf-arm64-v8a/lib/libprotobuf.a protobuf-android-libs/libs/arm64-v8a/
          cp artifacts/libprotobuf-x86/lib/libprotobuf.a protobuf-android-libs/libs/x86/
          cp artifacts/libprotobuf-x86_64/lib/libprotobuf.a protobuf-android-libs/libs/x86_64/

      - name: Create zip archive
        run: |
          zip -r protobuf-android-libs.zip protobuf-android-libs

      - name: Upload final archive
        uses: actions/upload-artifact@v4
        with:
          name: protobuf-android-libs
          path: protobuf-android-libs.zip
