name: Build Protobuf + Android

on: [push, pull_request, workflow_dispatch]

jobs:
  build-protobuf:
    runs-on: ubuntu-latest
    outputs:
      protoc-path: ${{ steps.install.outputs.protoc_path }}
    steps:
      - uses: actions/checkout@v4
        with: { repository: protocolbuffers/protobuf }
      - id: cache-protobuf
        uses: actions/cache@v3
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf-${{ hashFiles('protobuf/**') }}
      - name: Build protoc if needed
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - id: install
        run: echo "protoc_path=$(which protoc)" >> $GITHUB_OUTPUT

  build-android:
    needs: build-protobuf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        # ваш Android проект
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '11'
      - name: Build with Gradle
        env:
          PROTOC: ${{ needs.build-protobuf.outputs.protoc-path }}
        run: ./gradlew clean build
